### ISSUE TITLE
defcall can not use in quote

### ISSUE THREAD

**Issue by rubyist1982** [sasa1977/exactor#21]
code like below can not work since i want to inject code from other module for grouping
`quote do`
 `  defcall get_any do`
           `    reply :ok`
     `  end`
`end`
but using get_any() it works

**Comment by sasa1977** [comment]
Sorry for the late reply, I was a bit busy. 

I'm able to reproduce the problem, but now I need to check some AST internals with Elixir team. However, I'll be out of town for two weeks, and I probably won't be able to do much about this problem until I return. So for the moment, the workaround is indeed to use `defcall get_any()` if you use it inside a `quote`, but I'll definitely see what can I do about it.

Thank you for reporting this!

**Comment by sasa1977** [comment]
This should be fixed on master. I'll publish the new version to hex later today or tomorrow.

**Comment by sasa1977** [comment]
FYI, I just pushed version `2.2.1` to hex.
