### ISSUE TITLE
Struct pattern matching error

### ISSUE THREAD

**Issue by Mazyod** [sasa1977/exactor#22]
Hello Saša, and thanks for making the 2.2.1 release!

I just had the time to try and upgrade my project and test the dependencies, and my ExActor GenServer is failing to properly pattern match against a struct.

Please consider the following code:

```elixir
defcall process(%Socks.Game{} = game) do
  IO.inspect game
  ...
end
```

Of course, the `%Socks.Game{}` is just used for pattern matching, however, when I hit the `IO.inspect`, the printed game is an empty `Socks.Game` struct, even though I've passed in a filled `Socks.Game` object.

I caught this during unit tests, so I cleaned the dependencies, installed v2.2.0, and everything worked again. Cleaned the dependencies again, installed v2.2.1, and the test broke again. That's to say, I'm pretty confident something slipped through the cracks in the v2.2.1 release.

**Comment by sasa1977** [comment]
Thanks for reporting this. I pushed a commit which fixes the problem. Could you give the master a try, and confirm that it works for you? If everything is fine, I'll push `2.2.2` to hex.

**Comment by Mazyod** [comment]
👍  awesome! Getting less warnings thanks to the 2.2.1 update, and the struct issue is fixed as well

**Comment by sasa1977** [comment]
@Mazyod Sorry it took a bit longer, but I finally found the time to push 2.2.2 to hex.
