### ISSUE TITLE
Support for Elixir 1.5 @impl

### ISSUE THREAD

**Issue by carusso** [sasa1977/exactor#29]
It doesn't appear that there's a way to use the @impl directive with ExActor.

In a GenServer using ExActor, I have a terminate() function.  If I use the @impl directive on it, I'm warned about not having the directive on the macro-generated call backs in the GenServer.

**Comment by sasa1977** [comment]
I've added automatic generation of `@impl` attributes for callback functions generated by ExActor. Could you please try it out from [this branch](https://github.com/sasa1977/exactor/tree/generate-impl-attributes) and let me know if it works for you?

**Comment by carusso** [comment]
I switched my dependency to the branch you referenced.  As expected, the ExActor classes I had that contained other callbacks like terminate() and handle_info() began emitting warnings when compiled.

No other behavior changes were detected in my software, so it looks to me like your change was good.
Thanks

**Comment by sasa1977** [comment]
Thanks! I'm away this week, so not sure if I'll find the time to merge/publish. At the latest, I'll do it next week.

**Comment by sasa1977** [comment]
FYI, I just published 2.2.4 to hex. Thanks for reporting this issue!
